### ISSUE TITLE
COMANDO PRA TOCAR MAC DEMARCO

### ISSUE THREAD

**Issue by appositum** [TERRIBL3/ALTAIR#1]
@TERRIBL3 pq sim

**Comment by TERRIBL3** [comment]
vdd vou fazer

**Comment by Lainweeb** [comment]
Não, tem que ser "Comando para trocar a voz mesmo"

**Comment by matheusyes** [comment]
@TERRIBL3  vayne lixo kkkkkkkkkkkkkkk
